// Code generated by protoc-gen-go. DO NOT EDIT.
// source: definitions.proto

package dialog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UUIDValue struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUIDValue) Reset()         { *m = UUIDValue{} }
func (m *UUIDValue) String() string { return proto.CompactTextString(m) }
func (*UUIDValue) ProtoMessage()    {}
func (*UUIDValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_definitions_3c5fbb43e1dabca6, []int{0}
}
func (m *UUIDValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUIDValue.Unmarshal(m, b)
}
func (m *UUIDValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUIDValue.Marshal(b, m, deterministic)
}
func (dst *UUIDValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUIDValue.Merge(dst, src)
}
func (m *UUIDValue) XXX_Size() int {
	return xxx_messageInfo_UUIDValue.Size(m)
}
func (m *UUIDValue) XXX_DiscardUnknown() {
	xxx_messageInfo_UUIDValue.DiscardUnknown(m)
}

var xxx_messageInfo_UUIDValue proto.InternalMessageInfo

func (m *UUIDValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type DialogOptions struct {
	Log                  string   `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DialogOptions) Reset()         { *m = DialogOptions{} }
func (m *DialogOptions) String() string { return proto.CompactTextString(m) }
func (*DialogOptions) ProtoMessage()    {}
func (*DialogOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_definitions_3c5fbb43e1dabca6, []int{1}
}
func (m *DialogOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DialogOptions.Unmarshal(m, b)
}
func (m *DialogOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DialogOptions.Marshal(b, m, deterministic)
}
func (dst *DialogOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DialogOptions.Merge(dst, src)
}
func (m *DialogOptions) XXX_Size() int {
	return xxx_messageInfo_DialogOptions.Size(m)
}
func (m *DialogOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DialogOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DialogOptions proto.InternalMessageInfo

func (m *DialogOptions) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

var E_Dlg = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*DialogOptions)(nil),
	Field:         100001,
	Name:          "dialog.dlg",
	Tag:           "bytes,100001,opt,name=dlg",
	Filename:      "definitions.proto",
}

func init() {
	proto.RegisterType((*UUIDValue)(nil), "dialog.UUIDValue")
	proto.RegisterType((*DialogOptions)(nil), "dialog.DialogOptions")
	proto.RegisterExtension(E_Dlg)
}

func init() { proto.RegisterFile("definitions.proto", fileDescriptor_definitions_3c5fbb43e1dabca6) }

var fileDescriptor_definitions_3c5fbb43e1dabca6 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x49, 0x4d, 0xcb,
	0xcc, 0xcb, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b,
	0xc9, 0x4c, 0xcc, 0xc9, 0x4f, 0x97, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b,
	0x26, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0x54,
	0x4a, 0x89, 0x16, 0x27, 0x27, 0xe6, 0x24, 0x16, 0x24, 0xe9, 0x43, 0x69, 0x88, 0xb0, 0x92, 0x22,
	0x17, 0x67, 0x68, 0xa8, 0xa7, 0x4b, 0x58, 0x62, 0x4e, 0x69, 0xaa, 0x90, 0x08, 0x17, 0x6b, 0x19,
	0x88, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe1, 0x28, 0x29, 0x72, 0xf1, 0xba, 0x80,
	0x6d, 0xf1, 0x2f, 0x00, 0x5b, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x93, 0x9f, 0x0e, 0x56, 0xc4, 0x19,
	0x04, 0x62, 0x5a, 0x79, 0x70, 0x31, 0xa7, 0xe4, 0xa4, 0x0b, 0xc9, 0xea, 0x41, 0x9c, 0xa1, 0x07,
	0x73, 0x86, 0x9e, 0x5b, 0x66, 0x6a, 0x4e, 0x0a, 0x54, 0x9f, 0xc4, 0xc2, 0x5e, 0x36, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x51, 0x3d, 0x88, 0xab, 0xf5, 0x50, 0x8c, 0x0d, 0x02, 0x19, 0xe1, 0x24, 0xf9,
	0xc8, 0x5e, 0x8c, 0x4b, 0x24, 0x33, 0x57, 0x2f, 0x25, 0x27, 0x5d, 0x2f, 0xbd, 0xa8, 0x20, 0x59,
	0xaf, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0xb5, 0x38, 0x89, 0x0d, 0x6c, 0xaa, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x8c, 0x68, 0x47, 0x32, 0x07, 0x01, 0x00, 0x00,
}
