// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package dialog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/types"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchPeerType int32

const (
	SearchPeerType_SEARCHPEERTYPE_UNKNOWN  SearchPeerType = 0
	SearchPeerType_SEARCHPEERTYPE_GROUPS   SearchPeerType = 1
	SearchPeerType_SEARCHPEERTYPE_CONTACTS SearchPeerType = 2
	SearchPeerType_SEARCHPEERTYPE_PUBLIC   SearchPeerType = 3
)

var SearchPeerType_name = map[int32]string{
	0: "SEARCHPEERTYPE_UNKNOWN",
	1: "SEARCHPEERTYPE_GROUPS",
	2: "SEARCHPEERTYPE_CONTACTS",
	3: "SEARCHPEERTYPE_PUBLIC",
}
var SearchPeerType_value = map[string]int32{
	"SEARCHPEERTYPE_UNKNOWN":  0,
	"SEARCHPEERTYPE_GROUPS":   1,
	"SEARCHPEERTYPE_CONTACTS": 2,
	"SEARCHPEERTYPE_PUBLIC":   3,
}

func (x SearchPeerType) String() string {
	return proto.EnumName(SearchPeerType_name, int32(x))
}
func (SearchPeerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{0}
}

type SearchContentType int32

const (
	SearchContentType_SEARCHCONTENTTYPE_UNKNOWN   SearchContentType = 0
	SearchContentType_SEARCHCONTENTTYPE_ANY       SearchContentType = 1
	SearchContentType_SEARCHCONTENTTYPE_TEXT      SearchContentType = 2
	SearchContentType_SEARCHCONTENTTYPE_LINKS     SearchContentType = 3
	SearchContentType_SEARCHCONTENTTYPE_DOCUMENTS SearchContentType = 4
	SearchContentType_SEARCHCONTENTTYPE_PHOTOS    SearchContentType = 5
)

var SearchContentType_name = map[int32]string{
	0: "SEARCHCONTENTTYPE_UNKNOWN",
	1: "SEARCHCONTENTTYPE_ANY",
	2: "SEARCHCONTENTTYPE_TEXT",
	3: "SEARCHCONTENTTYPE_LINKS",
	4: "SEARCHCONTENTTYPE_DOCUMENTS",
	5: "SEARCHCONTENTTYPE_PHOTOS",
}
var SearchContentType_value = map[string]int32{
	"SEARCHCONTENTTYPE_UNKNOWN":   0,
	"SEARCHCONTENTTYPE_ANY":       1,
	"SEARCHCONTENTTYPE_TEXT":      2,
	"SEARCHCONTENTTYPE_LINKS":     3,
	"SEARCHCONTENTTYPE_DOCUMENTS": 4,
	"SEARCHCONTENTTYPE_PHOTOS":    5,
}

func (x SearchContentType) String() string {
	return proto.EnumName(SearchContentType_name, int32(x))
}
func (SearchContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{1}
}

type SimpleContactSearchCondition struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleContactSearchCondition) Reset()         { *m = SimpleContactSearchCondition{} }
func (m *SimpleContactSearchCondition) String() string { return proto.CompactTextString(m) }
func (*SimpleContactSearchCondition) ProtoMessage()    {}
func (*SimpleContactSearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{0}
}
func (m *SimpleContactSearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleContactSearchCondition.Unmarshal(m, b)
}
func (m *SimpleContactSearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleContactSearchCondition.Marshal(b, m, deterministic)
}
func (dst *SimpleContactSearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleContactSearchCondition.Merge(dst, src)
}
func (m *SimpleContactSearchCondition) XXX_Size() int {
	return xxx_messageInfo_SimpleContactSearchCondition.Size(m)
}
func (m *SimpleContactSearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleContactSearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleContactSearchCondition proto.InternalMessageInfo

func (m *SimpleContactSearchCondition) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SimpleMessageSearchCondition struct {
	Peer                 *Peer             `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	ContentType          SearchContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,enum=dialog.SearchContentType" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimpleMessageSearchCondition) Reset()         { *m = SimpleMessageSearchCondition{} }
func (m *SimpleMessageSearchCondition) String() string { return proto.CompactTextString(m) }
func (*SimpleMessageSearchCondition) ProtoMessage()    {}
func (*SimpleMessageSearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{1}
}
func (m *SimpleMessageSearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessageSearchCondition.Unmarshal(m, b)
}
func (m *SimpleMessageSearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessageSearchCondition.Marshal(b, m, deterministic)
}
func (dst *SimpleMessageSearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessageSearchCondition.Merge(dst, src)
}
func (m *SimpleMessageSearchCondition) XXX_Size() int {
	return xxx_messageInfo_SimpleMessageSearchCondition.Size(m)
}
func (m *SimpleMessageSearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessageSearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessageSearchCondition proto.InternalMessageInfo

func (m *SimpleMessageSearchCondition) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *SimpleMessageSearchCondition) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SimpleMessageSearchCondition) GetContentType() SearchContentType {
	if m != nil {
		return m.ContentType
	}
	return SearchContentType_SEARCHCONTENTTYPE_UNKNOWN
}

type SimplePeerSearchCondition struct {
	PeerType             SearchPeerType        `protobuf:"varint,1,opt,name=peer_type,json=peerType,enum=dialog.SearchPeerType" json:"peer_type,omitempty"`
	Text                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SimplePeerSearchCondition) Reset()         { *m = SimplePeerSearchCondition{} }
func (m *SimplePeerSearchCondition) String() string { return proto.CompactTextString(m) }
func (*SimplePeerSearchCondition) ProtoMessage()    {}
func (*SimplePeerSearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{2}
}
func (m *SimplePeerSearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimplePeerSearchCondition.Unmarshal(m, b)
}
func (m *SimplePeerSearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimplePeerSearchCondition.Marshal(b, m, deterministic)
}
func (dst *SimplePeerSearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimplePeerSearchCondition.Merge(dst, src)
}
func (m *SimplePeerSearchCondition) XXX_Size() int {
	return xxx_messageInfo_SimplePeerSearchCondition.Size(m)
}
func (m *SimplePeerSearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SimplePeerSearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SimplePeerSearchCondition proto.InternalMessageInfo

func (m *SimplePeerSearchCondition) GetPeerType() SearchPeerType {
	if m != nil {
		return m.PeerType
	}
	return SearchPeerType_SEARCHPEERTYPE_UNKNOWN
}

func (m *SimplePeerSearchCondition) GetText() *wrappers.StringValue {
	if m != nil {
		return m.Text
	}
	return nil
}

type SimpleUserProfileSearchCondition struct {
	QueryString          string   `protobuf:"bytes,1,opt,name=query_string,json=queryString" json:"query_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleUserProfileSearchCondition) Reset()         { *m = SimpleUserProfileSearchCondition{} }
func (m *SimpleUserProfileSearchCondition) String() string { return proto.CompactTextString(m) }
func (*SimpleUserProfileSearchCondition) ProtoMessage()    {}
func (*SimpleUserProfileSearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{3}
}
func (m *SimpleUserProfileSearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleUserProfileSearchCondition.Unmarshal(m, b)
}
func (m *SimpleUserProfileSearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleUserProfileSearchCondition.Marshal(b, m, deterministic)
}
func (dst *SimpleUserProfileSearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleUserProfileSearchCondition.Merge(dst, src)
}
func (m *SimpleUserProfileSearchCondition) XXX_Size() int {
	return xxx_messageInfo_SimpleUserProfileSearchCondition.Size(m)
}
func (m *SimpleUserProfileSearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleUserProfileSearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleUserProfileSearchCondition proto.InternalMessageInfo

func (m *SimpleUserProfileSearchCondition) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

type Criterion struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Criterion) Reset()         { *m = Criterion{} }
func (m *Criterion) String() string { return proto.CompactTextString(m) }
func (*Criterion) ProtoMessage()    {}
func (*Criterion) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{4}
}
func (m *Criterion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Criterion.Unmarshal(m, b)
}
func (m *Criterion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Criterion.Marshal(b, m, deterministic)
}
func (dst *Criterion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Criterion.Merge(dst, src)
}
func (m *Criterion) XXX_Size() int {
	return xxx_messageInfo_Criterion.Size(m)
}
func (m *Criterion) XXX_DiscardUnknown() {
	xxx_messageInfo_Criterion.DiscardUnknown(m)
}

var xxx_messageInfo_Criterion proto.InternalMessageInfo

type SimpleSearchCondition struct {
	// Types that are valid to be assigned to Criterion:
	//	*SimpleSearchCondition_Contact
	//	*SimpleSearchCondition_Message
	//	*SimpleSearchCondition_Peer
	//	*SimpleSearchCondition_UserProfile
	Criterion            isSimpleSearchCondition_Criterion `protobuf_oneof:"criterion"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SimpleSearchCondition) Reset()         { *m = SimpleSearchCondition{} }
func (m *SimpleSearchCondition) String() string { return proto.CompactTextString(m) }
func (*SimpleSearchCondition) ProtoMessage()    {}
func (*SimpleSearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{5}
}
func (m *SimpleSearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleSearchCondition.Unmarshal(m, b)
}
func (m *SimpleSearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleSearchCondition.Marshal(b, m, deterministic)
}
func (dst *SimpleSearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleSearchCondition.Merge(dst, src)
}
func (m *SimpleSearchCondition) XXX_Size() int {
	return xxx_messageInfo_SimpleSearchCondition.Size(m)
}
func (m *SimpleSearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleSearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleSearchCondition proto.InternalMessageInfo

type isSimpleSearchCondition_Criterion interface {
	isSimpleSearchCondition_Criterion()
}

type SimpleSearchCondition_Contact struct {
	Contact *SimpleContactSearchCondition `protobuf:"bytes,1,opt,name=contact,oneof"`
}
type SimpleSearchCondition_Message struct {
	Message *SimpleMessageSearchCondition `protobuf:"bytes,2,opt,name=message,oneof"`
}
type SimpleSearchCondition_Peer struct {
	Peer *SimplePeerSearchCondition `protobuf:"bytes,3,opt,name=peer,oneof"`
}
type SimpleSearchCondition_UserProfile struct {
	UserProfile *SimpleUserProfileSearchCondition `protobuf:"bytes,4,opt,name=userProfile,oneof"`
}

func (*SimpleSearchCondition_Contact) isSimpleSearchCondition_Criterion()     {}
func (*SimpleSearchCondition_Message) isSimpleSearchCondition_Criterion()     {}
func (*SimpleSearchCondition_Peer) isSimpleSearchCondition_Criterion()        {}
func (*SimpleSearchCondition_UserProfile) isSimpleSearchCondition_Criterion() {}

func (m *SimpleSearchCondition) GetCriterion() isSimpleSearchCondition_Criterion {
	if m != nil {
		return m.Criterion
	}
	return nil
}

func (m *SimpleSearchCondition) GetContact() *SimpleContactSearchCondition {
	if x, ok := m.GetCriterion().(*SimpleSearchCondition_Contact); ok {
		return x.Contact
	}
	return nil
}

func (m *SimpleSearchCondition) GetMessage() *SimpleMessageSearchCondition {
	if x, ok := m.GetCriterion().(*SimpleSearchCondition_Message); ok {
		return x.Message
	}
	return nil
}

func (m *SimpleSearchCondition) GetPeer() *SimplePeerSearchCondition {
	if x, ok := m.GetCriterion().(*SimpleSearchCondition_Peer); ok {
		return x.Peer
	}
	return nil
}

func (m *SimpleSearchCondition) GetUserProfile() *SimpleUserProfileSearchCondition {
	if x, ok := m.GetCriterion().(*SimpleSearchCondition_UserProfile); ok {
		return x.UserProfile
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SimpleSearchCondition) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SimpleSearchCondition_OneofMarshaler, _SimpleSearchCondition_OneofUnmarshaler, _SimpleSearchCondition_OneofSizer, []interface{}{
		(*SimpleSearchCondition_Contact)(nil),
		(*SimpleSearchCondition_Message)(nil),
		(*SimpleSearchCondition_Peer)(nil),
		(*SimpleSearchCondition_UserProfile)(nil),
	}
}

func _SimpleSearchCondition_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SimpleSearchCondition)
	// criterion
	switch x := m.Criterion.(type) {
	case *SimpleSearchCondition_Contact:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Contact); err != nil {
			return err
		}
	case *SimpleSearchCondition_Message:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Message); err != nil {
			return err
		}
	case *SimpleSearchCondition_Peer:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Peer); err != nil {
			return err
		}
	case *SimpleSearchCondition_UserProfile:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserProfile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SimpleSearchCondition.Criterion has unexpected type %T", x)
	}
	return nil
}

func _SimpleSearchCondition_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SimpleSearchCondition)
	switch tag {
	case 1: // criterion.contact
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SimpleContactSearchCondition)
		err := b.DecodeMessage(msg)
		m.Criterion = &SimpleSearchCondition_Contact{msg}
		return true, err
	case 2: // criterion.message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SimpleMessageSearchCondition)
		err := b.DecodeMessage(msg)
		m.Criterion = &SimpleSearchCondition_Message{msg}
		return true, err
	case 3: // criterion.peer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SimplePeerSearchCondition)
		err := b.DecodeMessage(msg)
		m.Criterion = &SimpleSearchCondition_Peer{msg}
		return true, err
	case 4: // criterion.userProfile
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SimpleUserProfileSearchCondition)
		err := b.DecodeMessage(msg)
		m.Criterion = &SimpleSearchCondition_UserProfile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SimpleSearchCondition_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SimpleSearchCondition)
	// criterion
	switch x := m.Criterion.(type) {
	case *SimpleSearchCondition_Contact:
		s := proto.Size(x.Contact)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SimpleSearchCondition_Message:
		s := proto.Size(x.Message)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SimpleSearchCondition_Peer:
		s := proto.Size(x.Peer)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SimpleSearchCondition_UserProfile:
		s := proto.Size(x.UserProfile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SearchCondition struct {
	// Types that are valid to be assigned to Body:
	//	*SearchCondition_SearchPeerTypeCondition
	//	*SearchCondition_SearchPieceText
	//	*SearchCondition_SearchAndCondition
	//	*SearchCondition_SearchOrCondition
	//	*SearchCondition_SearchPeerCondition
	//	*SearchCondition_SearchPeerContentType
	//	*SearchCondition_SearchSenderIdConfition
	Body                 isSearchCondition_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchCondition) Reset()         { *m = SearchCondition{} }
func (m *SearchCondition) String() string { return proto.CompactTextString(m) }
func (*SearchCondition) ProtoMessage()    {}
func (*SearchCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{6}
}
func (m *SearchCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCondition.Unmarshal(m, b)
}
func (m *SearchCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCondition.Marshal(b, m, deterministic)
}
func (dst *SearchCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCondition.Merge(dst, src)
}
func (m *SearchCondition) XXX_Size() int {
	return xxx_messageInfo_SearchCondition.Size(m)
}
func (m *SearchCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCondition proto.InternalMessageInfo

type isSearchCondition_Body interface {
	isSearchCondition_Body()
}

type SearchCondition_SearchPeerTypeCondition struct {
	SearchPeerTypeCondition *SearchPeerTypeCondition `protobuf:"bytes,1,opt,name=searchPeerTypeCondition,oneof"`
}
type SearchCondition_SearchPieceText struct {
	SearchPieceText *SearchPieceText `protobuf:"bytes,2,opt,name=searchPieceText,oneof"`
}
type SearchCondition_SearchAndCondition struct {
	SearchAndCondition *SearchAndCondition `protobuf:"bytes,3,opt,name=searchAndCondition,oneof"`
}
type SearchCondition_SearchOrCondition struct {
	SearchOrCondition *SearchOrCondition `protobuf:"bytes,4,opt,name=searchOrCondition,oneof"`
}
type SearchCondition_SearchPeerCondition struct {
	SearchPeerCondition *SearchPeerCondition `protobuf:"bytes,5,opt,name=searchPeerCondition,oneof"`
}
type SearchCondition_SearchPeerContentType struct {
	SearchPeerContentType *SearchPeerContentType `protobuf:"bytes,6,opt,name=searchPeerContentType,oneof"`
}
type SearchCondition_SearchSenderIdConfition struct {
	SearchSenderIdConfition *SearchSenderIdConfition `protobuf:"bytes,7,opt,name=searchSenderIdConfition,oneof"`
}

func (*SearchCondition_SearchPeerTypeCondition) isSearchCondition_Body() {}
func (*SearchCondition_SearchPieceText) isSearchCondition_Body()         {}
func (*SearchCondition_SearchAndCondition) isSearchCondition_Body()      {}
func (*SearchCondition_SearchOrCondition) isSearchCondition_Body()       {}
func (*SearchCondition_SearchPeerCondition) isSearchCondition_Body()     {}
func (*SearchCondition_SearchPeerContentType) isSearchCondition_Body()   {}
func (*SearchCondition_SearchSenderIdConfition) isSearchCondition_Body() {}

func (m *SearchCondition) GetBody() isSearchCondition_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *SearchCondition) GetSearchPeerTypeCondition() *SearchPeerTypeCondition {
	if x, ok := m.GetBody().(*SearchCondition_SearchPeerTypeCondition); ok {
		return x.SearchPeerTypeCondition
	}
	return nil
}

func (m *SearchCondition) GetSearchPieceText() *SearchPieceText {
	if x, ok := m.GetBody().(*SearchCondition_SearchPieceText); ok {
		return x.SearchPieceText
	}
	return nil
}

func (m *SearchCondition) GetSearchAndCondition() *SearchAndCondition {
	if x, ok := m.GetBody().(*SearchCondition_SearchAndCondition); ok {
		return x.SearchAndCondition
	}
	return nil
}

func (m *SearchCondition) GetSearchOrCondition() *SearchOrCondition {
	if x, ok := m.GetBody().(*SearchCondition_SearchOrCondition); ok {
		return x.SearchOrCondition
	}
	return nil
}

func (m *SearchCondition) GetSearchPeerCondition() *SearchPeerCondition {
	if x, ok := m.GetBody().(*SearchCondition_SearchPeerCondition); ok {
		return x.SearchPeerCondition
	}
	return nil
}

func (m *SearchCondition) GetSearchPeerContentType() *SearchPeerContentType {
	if x, ok := m.GetBody().(*SearchCondition_SearchPeerContentType); ok {
		return x.SearchPeerContentType
	}
	return nil
}

func (m *SearchCondition) GetSearchSenderIdConfition() *SearchSenderIdConfition {
	if x, ok := m.GetBody().(*SearchCondition_SearchSenderIdConfition); ok {
		return x.SearchSenderIdConfition
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SearchCondition) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SearchCondition_OneofMarshaler, _SearchCondition_OneofUnmarshaler, _SearchCondition_OneofSizer, []interface{}{
		(*SearchCondition_SearchPeerTypeCondition)(nil),
		(*SearchCondition_SearchPieceText)(nil),
		(*SearchCondition_SearchAndCondition)(nil),
		(*SearchCondition_SearchOrCondition)(nil),
		(*SearchCondition_SearchPeerCondition)(nil),
		(*SearchCondition_SearchPeerContentType)(nil),
		(*SearchCondition_SearchSenderIdConfition)(nil),
	}
}

func _SearchCondition_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SearchCondition)
	// body
	switch x := m.Body.(type) {
	case *SearchCondition_SearchPeerTypeCondition:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchPeerTypeCondition); err != nil {
			return err
		}
	case *SearchCondition_SearchPieceText:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchPieceText); err != nil {
			return err
		}
	case *SearchCondition_SearchAndCondition:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchAndCondition); err != nil {
			return err
		}
	case *SearchCondition_SearchOrCondition:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchOrCondition); err != nil {
			return err
		}
	case *SearchCondition_SearchPeerCondition:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchPeerCondition); err != nil {
			return err
		}
	case *SearchCondition_SearchPeerContentType:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchPeerContentType); err != nil {
			return err
		}
	case *SearchCondition_SearchSenderIdConfition:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SearchSenderIdConfition); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SearchCondition.Body has unexpected type %T", x)
	}
	return nil
}

func _SearchCondition_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SearchCondition)
	switch tag {
	case 1: // body.searchPeerTypeCondition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchPeerTypeCondition)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchPeerTypeCondition{msg}
		return true, err
	case 2: // body.searchPieceText
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchPieceText)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchPieceText{msg}
		return true, err
	case 3: // body.searchAndCondition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchAndCondition)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchAndCondition{msg}
		return true, err
	case 4: // body.searchOrCondition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchOrCondition)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchOrCondition{msg}
		return true, err
	case 5: // body.searchPeerCondition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchPeerCondition)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchPeerCondition{msg}
		return true, err
	case 6: // body.searchPeerContentType
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchPeerContentType)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchPeerContentType{msg}
		return true, err
	case 7: // body.searchSenderIdConfition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SearchSenderIdConfition)
		err := b.DecodeMessage(msg)
		m.Body = &SearchCondition_SearchSenderIdConfition{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SearchCondition_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SearchCondition)
	// body
	switch x := m.Body.(type) {
	case *SearchCondition_SearchPeerTypeCondition:
		s := proto.Size(x.SearchPeerTypeCondition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchPieceText:
		s := proto.Size(x.SearchPieceText)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchAndCondition:
		s := proto.Size(x.SearchAndCondition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchOrCondition:
		s := proto.Size(x.SearchOrCondition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchPeerCondition:
		s := proto.Size(x.SearchPeerCondition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchPeerContentType:
		s := proto.Size(x.SearchPeerContentType)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SearchCondition_SearchSenderIdConfition:
		s := proto.Size(x.SearchSenderIdConfition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Search peer type condition
// peerType Peer type for searching
type SearchPeerTypeCondition struct {
	PeerType             SearchPeerType `protobuf:"varint,1,opt,name=peer_type,json=peerType,enum=dialog.SearchPeerType" json:"peer_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchPeerTypeCondition) Reset()         { *m = SearchPeerTypeCondition{} }
func (m *SearchPeerTypeCondition) String() string { return proto.CompactTextString(m) }
func (*SearchPeerTypeCondition) ProtoMessage()    {}
func (*SearchPeerTypeCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{7}
}
func (m *SearchPeerTypeCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPeerTypeCondition.Unmarshal(m, b)
}
func (m *SearchPeerTypeCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPeerTypeCondition.Marshal(b, m, deterministic)
}
func (dst *SearchPeerTypeCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPeerTypeCondition.Merge(dst, src)
}
func (m *SearchPeerTypeCondition) XXX_Size() int {
	return xxx_messageInfo_SearchPeerTypeCondition.Size(m)
}
func (m *SearchPeerTypeCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPeerTypeCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPeerTypeCondition proto.InternalMessageInfo

func (m *SearchPeerTypeCondition) GetPeerType() SearchPeerType {
	if m != nil {
		return m.PeerType
	}
	return SearchPeerType_SEARCHPEERTYPE_UNKNOWN
}

// Search peer name condition
// query Search query
type SearchPieceText struct {
	Query                string   `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPieceText) Reset()         { *m = SearchPieceText{} }
func (m *SearchPieceText) String() string { return proto.CompactTextString(m) }
func (*SearchPieceText) ProtoMessage()    {}
func (*SearchPieceText) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{8}
}
func (m *SearchPieceText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPieceText.Unmarshal(m, b)
}
func (m *SearchPieceText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPieceText.Marshal(b, m, deterministic)
}
func (dst *SearchPieceText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPieceText.Merge(dst, src)
}
func (m *SearchPieceText) XXX_Size() int {
	return xxx_messageInfo_SearchPieceText.Size(m)
}
func (m *SearchPieceText) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPieceText.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPieceText proto.InternalMessageInfo

func (m *SearchPieceText) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

// Search AND condion
// andQuery And Query
type SearchAndCondition struct {
	AndQuery             []*SearchCondition `protobuf:"bytes,1,rep,name=and_query,json=andQuery" json:"and_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchAndCondition) Reset()         { *m = SearchAndCondition{} }
func (m *SearchAndCondition) String() string { return proto.CompactTextString(m) }
func (*SearchAndCondition) ProtoMessage()    {}
func (*SearchAndCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{9}
}
func (m *SearchAndCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAndCondition.Unmarshal(m, b)
}
func (m *SearchAndCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAndCondition.Marshal(b, m, deterministic)
}
func (dst *SearchAndCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAndCondition.Merge(dst, src)
}
func (m *SearchAndCondition) XXX_Size() int {
	return xxx_messageInfo_SearchAndCondition.Size(m)
}
func (m *SearchAndCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAndCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAndCondition proto.InternalMessageInfo

func (m *SearchAndCondition) GetAndQuery() []*SearchCondition {
	if m != nil {
		return m.AndQuery
	}
	return nil
}

// Search OR condition
// orQuery Or Query
type SearchOrCondition struct {
	OrQuery              []*SearchCondition `protobuf:"bytes,2,rep,name=or_query,json=orQuery" json:"or_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchOrCondition) Reset()         { *m = SearchOrCondition{} }
func (m *SearchOrCondition) String() string { return proto.CompactTextString(m) }
func (*SearchOrCondition) ProtoMessage()    {}
func (*SearchOrCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{10}
}
func (m *SearchOrCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchOrCondition.Unmarshal(m, b)
}
func (m *SearchOrCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchOrCondition.Marshal(b, m, deterministic)
}
func (dst *SearchOrCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchOrCondition.Merge(dst, src)
}
func (m *SearchOrCondition) XXX_Size() int {
	return xxx_messageInfo_SearchOrCondition.Size(m)
}
func (m *SearchOrCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchOrCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchOrCondition proto.InternalMessageInfo

func (m *SearchOrCondition) GetOrQuery() []*SearchCondition {
	if m != nil {
		return m.OrQuery
	}
	return nil
}

// Serch Peer condition
// peer Peer condition
type SearchPeerCondition struct {
	Peer                 *OutPeer `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPeerCondition) Reset()         { *m = SearchPeerCondition{} }
func (m *SearchPeerCondition) String() string { return proto.CompactTextString(m) }
func (*SearchPeerCondition) ProtoMessage()    {}
func (*SearchPeerCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{11}
}
func (m *SearchPeerCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPeerCondition.Unmarshal(m, b)
}
func (m *SearchPeerCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPeerCondition.Marshal(b, m, deterministic)
}
func (dst *SearchPeerCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPeerCondition.Merge(dst, src)
}
func (m *SearchPeerCondition) XXX_Size() int {
	return xxx_messageInfo_SearchPeerCondition.Size(m)
}
func (m *SearchPeerCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPeerCondition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPeerCondition proto.InternalMessageInfo

func (m *SearchPeerCondition) GetPeer() *OutPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

// Search content type condition
// contentType Content Type
type SearchPeerContentType struct {
	ContentType          SearchContentType `protobuf:"varint,1,opt,name=content_type,json=contentType,enum=dialog.SearchContentType" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchPeerContentType) Reset()         { *m = SearchPeerContentType{} }
func (m *SearchPeerContentType) String() string { return proto.CompactTextString(m) }
func (*SearchPeerContentType) ProtoMessage()    {}
func (*SearchPeerContentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{12}
}
func (m *SearchPeerContentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPeerContentType.Unmarshal(m, b)
}
func (m *SearchPeerContentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPeerContentType.Marshal(b, m, deterministic)
}
func (dst *SearchPeerContentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPeerContentType.Merge(dst, src)
}
func (m *SearchPeerContentType) XXX_Size() int {
	return xxx_messageInfo_SearchPeerContentType.Size(m)
}
func (m *SearchPeerContentType) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPeerContentType.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPeerContentType proto.InternalMessageInfo

func (m *SearchPeerContentType) GetContentType() SearchContentType {
	if m != nil {
		return m.ContentType
	}
	return SearchContentType_SEARCHCONTENTTYPE_UNKNOWN
}

// Searching sender uid condition
// senderId sender UID
type SearchSenderIdConfition struct {
	SenderId             int32    `protobuf:"varint,1,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchSenderIdConfition) Reset()         { *m = SearchSenderIdConfition{} }
func (m *SearchSenderIdConfition) String() string { return proto.CompactTextString(m) }
func (*SearchSenderIdConfition) ProtoMessage()    {}
func (*SearchSenderIdConfition) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{13}
}
func (m *SearchSenderIdConfition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchSenderIdConfition.Unmarshal(m, b)
}
func (m *SearchSenderIdConfition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchSenderIdConfition.Marshal(b, m, deterministic)
}
func (dst *SearchSenderIdConfition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchSenderIdConfition.Merge(dst, src)
}
func (m *SearchSenderIdConfition) XXX_Size() int {
	return xxx_messageInfo_SearchSenderIdConfition.Size(m)
}
func (m *SearchSenderIdConfition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchSenderIdConfition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchSenderIdConfition proto.InternalMessageInfo

func (m *SearchSenderIdConfition) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

// Peer search result
// peer Peer information
// title Peer title
// description Description
// membersCount Members count
// dateCreated Group Creation Date
// creator Group Creator uid
// isPublic Is group public
type PeerSearchResult struct {
	Peer                 *Peer                 `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Shortname            *wrappers.StringValue `protobuf:"bytes,9,opt,name=shortname" json:"shortname,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	MembersCount         *wrappers.Int32Value  `protobuf:"bytes,4,opt,name=members_count,json=membersCount" json:"members_count,omitempty"`
	DateCreated          int64                 `protobuf:"varint,5,opt,name=date_created,json=dateCreated" json:"date_created,omitempty"`
	Creator              *wrappers.Int32Value  `protobuf:"bytes,6,opt,name=creator" json:"creator,omitempty"`
	IsPublic             *wrappers.BoolValue   `protobuf:"bytes,7,opt,name=is_public,json=isPublic" json:"is_public,omitempty"`
	IsJoined             *wrappers.BoolValue   `protobuf:"bytes,8,opt,name=is_joined,json=isJoined" json:"is_joined,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PeerSearchResult) Reset()         { *m = PeerSearchResult{} }
func (m *PeerSearchResult) String() string { return proto.CompactTextString(m) }
func (*PeerSearchResult) ProtoMessage()    {}
func (*PeerSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{14}
}
func (m *PeerSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerSearchResult.Unmarshal(m, b)
}
func (m *PeerSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerSearchResult.Marshal(b, m, deterministic)
}
func (dst *PeerSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerSearchResult.Merge(dst, src)
}
func (m *PeerSearchResult) XXX_Size() int {
	return xxx_messageInfo_PeerSearchResult.Size(m)
}
func (m *PeerSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_PeerSearchResult proto.InternalMessageInfo

func (m *PeerSearchResult) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *PeerSearchResult) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PeerSearchResult) GetShortname() *wrappers.StringValue {
	if m != nil {
		return m.Shortname
	}
	return nil
}

func (m *PeerSearchResult) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *PeerSearchResult) GetMembersCount() *wrappers.Int32Value {
	if m != nil {
		return m.MembersCount
	}
	return nil
}

func (m *PeerSearchResult) GetDateCreated() int64 {
	if m != nil {
		return m.DateCreated
	}
	return 0
}

func (m *PeerSearchResult) GetCreator() *wrappers.Int32Value {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *PeerSearchResult) GetIsPublic() *wrappers.BoolValue {
	if m != nil {
		return m.IsPublic
	}
	return nil
}

func (m *PeerSearchResult) GetIsJoined() *wrappers.BoolValue {
	if m != nil {
		return m.IsJoined
	}
	return nil
}

// Performing peer search
type RequestPeerSearch struct {
	Query                []*SearchCondition   `protobuf:"bytes,1,rep,name=query" json:"query,omitempty"`
	Optimizations        []UpdateOptimization `protobuf:"varint,2,rep,packed,name=optimizations,enum=dialog.UpdateOptimization" json:"optimizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestPeerSearch) Reset()         { *m = RequestPeerSearch{} }
func (m *RequestPeerSearch) String() string { return proto.CompactTextString(m) }
func (*RequestPeerSearch) ProtoMessage()    {}
func (*RequestPeerSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{15}
}
func (m *RequestPeerSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPeerSearch.Unmarshal(m, b)
}
func (m *RequestPeerSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPeerSearch.Marshal(b, m, deterministic)
}
func (dst *RequestPeerSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPeerSearch.Merge(dst, src)
}
func (m *RequestPeerSearch) XXX_Size() int {
	return xxx_messageInfo_RequestPeerSearch.Size(m)
}
func (m *RequestPeerSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPeerSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPeerSearch proto.InternalMessageInfo

func (m *RequestPeerSearch) GetQuery() []*SearchCondition {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *RequestPeerSearch) GetOptimizations() []UpdateOptimization {
	if m != nil {
		return m.Optimizations
	}
	return nil
}

type ResponsePeerSearch struct {
	SearchResults        []*PeerSearchResult `protobuf:"bytes,1,rep,name=search_results,json=searchResults" json:"search_results,omitempty"`
	Users                []*User             `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Groups               []*Group            `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	UserPeers            []*UserOutPeer      `protobuf:"bytes,4,rep,name=user_peers,json=userPeers" json:"user_peers,omitempty"`
	GroupPeers           []*GroupOutPeer     `protobuf:"bytes,5,rep,name=group_peers,json=groupPeers" json:"group_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ResponsePeerSearch) Reset()         { *m = ResponsePeerSearch{} }
func (m *ResponsePeerSearch) String() string { return proto.CompactTextString(m) }
func (*ResponsePeerSearch) ProtoMessage()    {}
func (*ResponsePeerSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{16}
}
func (m *ResponsePeerSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePeerSearch.Unmarshal(m, b)
}
func (m *ResponsePeerSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePeerSearch.Marshal(b, m, deterministic)
}
func (dst *ResponsePeerSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePeerSearch.Merge(dst, src)
}
func (m *ResponsePeerSearch) XXX_Size() int {
	return xxx_messageInfo_ResponsePeerSearch.Size(m)
}
func (m *ResponsePeerSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePeerSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePeerSearch proto.InternalMessageInfo

func (m *ResponsePeerSearch) GetSearchResults() []*PeerSearchResult {
	if m != nil {
		return m.SearchResults
	}
	return nil
}

func (m *ResponsePeerSearch) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ResponsePeerSearch) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ResponsePeerSearch) GetUserPeers() []*UserOutPeer {
	if m != nil {
		return m.UserPeers
	}
	return nil
}

func (m *ResponsePeerSearch) GetGroupPeers() []*GroupOutPeer {
	if m != nil {
		return m.GroupPeers
	}
	return nil
}

// Resolve peer by shortname
type RequestResolvePeer struct {
	Shortname            string   `protobuf:"bytes,1,opt,name=shortname" json:"shortname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResolvePeer) Reset()         { *m = RequestResolvePeer{} }
func (m *RequestResolvePeer) String() string { return proto.CompactTextString(m) }
func (*RequestResolvePeer) ProtoMessage()    {}
func (*RequestResolvePeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{17}
}
func (m *RequestResolvePeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResolvePeer.Unmarshal(m, b)
}
func (m *RequestResolvePeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResolvePeer.Marshal(b, m, deterministic)
}
func (dst *RequestResolvePeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResolvePeer.Merge(dst, src)
}
func (m *RequestResolvePeer) XXX_Size() int {
	return xxx_messageInfo_RequestResolvePeer.Size(m)
}
func (m *RequestResolvePeer) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResolvePeer.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResolvePeer proto.InternalMessageInfo

func (m *RequestResolvePeer) GetShortname() string {
	if m != nil {
		return m.Shortname
	}
	return ""
}

type ResponseResolvePeer struct {
	Peer                 *OutPeer `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseResolvePeer) Reset()         { *m = ResponseResolvePeer{} }
func (m *ResponseResolvePeer) String() string { return proto.CompactTextString(m) }
func (*ResponseResolvePeer) ProtoMessage()    {}
func (*ResponseResolvePeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{18}
}
func (m *ResponseResolvePeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseResolvePeer.Unmarshal(m, b)
}
func (m *ResponseResolvePeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseResolvePeer.Marshal(b, m, deterministic)
}
func (dst *ResponseResolvePeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseResolvePeer.Merge(dst, src)
}
func (m *ResponseResolvePeer) XXX_Size() int {
	return xxx_messageInfo_ResponseResolvePeer.Size(m)
}
func (m *ResponseResolvePeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseResolvePeer.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseResolvePeer proto.InternalMessageInfo

func (m *ResponseResolvePeer) GetPeer() *OutPeer {
	if m != nil {
		return m.Peer
	}
	return nil
}

// Message container
// peer Message Peer
// rid Message Random Id
// date Message Date
// senderId Message sender UID
// content Message content
type MessageSearchResult struct {
	Peer                 *Peer           `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	Rid                  int64           `protobuf:"varint,2,opt,name=rid" json:"rid,omitempty"`
	Date                 int64           `protobuf:"varint,3,opt,name=date" json:"date,omitempty"`
	SenderId             int32           `protobuf:"varint,4,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	Content              *MessageContent `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MessageSearchResult) Reset()         { *m = MessageSearchResult{} }
func (m *MessageSearchResult) String() string { return proto.CompactTextString(m) }
func (*MessageSearchResult) ProtoMessage()    {}
func (*MessageSearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{19}
}
func (m *MessageSearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSearchResult.Unmarshal(m, b)
}
func (m *MessageSearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSearchResult.Marshal(b, m, deterministic)
}
func (dst *MessageSearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSearchResult.Merge(dst, src)
}
func (m *MessageSearchResult) XXX_Size() int {
	return xxx_messageInfo_MessageSearchResult.Size(m)
}
func (m *MessageSearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSearchResult proto.InternalMessageInfo

func (m *MessageSearchResult) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *MessageSearchResult) GetRid() int64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *MessageSearchResult) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *MessageSearchResult) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MessageSearchResult) GetContent() *MessageContent {
	if m != nil {
		return m.Content
	}
	return nil
}

// Message Search result container
type MessageSearchItem struct {
	Result               *MessageSearchResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageSearchItem) Reset()         { *m = MessageSearchItem{} }
func (m *MessageSearchItem) String() string { return proto.CompactTextString(m) }
func (*MessageSearchItem) ProtoMessage()    {}
func (*MessageSearchItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{20}
}
func (m *MessageSearchItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSearchItem.Unmarshal(m, b)
}
func (m *MessageSearchItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSearchItem.Marshal(b, m, deterministic)
}
func (dst *MessageSearchItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSearchItem.Merge(dst, src)
}
func (m *MessageSearchItem) XXX_Size() int {
	return xxx_messageInfo_MessageSearchItem.Size(m)
}
func (m *MessageSearchItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSearchItem.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSearchItem proto.InternalMessageInfo

func (m *MessageSearchItem) GetResult() *MessageSearchResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// Search Result
type ResponseMessageSearchResponse struct {
	SearchResults        []*MessageSearchItem `protobuf:"bytes,1,rep,name=search_results,json=searchResults" json:"search_results,omitempty"`
	Users                []*User              `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Groups               []*Group             `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	LoadMoreState        *wrappers.BytesValue `protobuf:"bytes,4,opt,name=load_more_state,json=loadMoreState" json:"load_more_state,omitempty"`
	UserOutPeers         []*UserOutPeer       `protobuf:"bytes,5,rep,name=user_out_peers,json=userOutPeers" json:"user_out_peers,omitempty"`
	GroupOutPeers        []*GroupOutPeer      `protobuf:"bytes,6,rep,name=group_out_peers,json=groupOutPeers" json:"group_out_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResponseMessageSearchResponse) Reset()         { *m = ResponseMessageSearchResponse{} }
func (m *ResponseMessageSearchResponse) String() string { return proto.CompactTextString(m) }
func (*ResponseMessageSearchResponse) ProtoMessage()    {}
func (*ResponseMessageSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{21}
}
func (m *ResponseMessageSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessageSearchResponse.Unmarshal(m, b)
}
func (m *ResponseMessageSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessageSearchResponse.Marshal(b, m, deterministic)
}
func (dst *ResponseMessageSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessageSearchResponse.Merge(dst, src)
}
func (m *ResponseMessageSearchResponse) XXX_Size() int {
	return xxx_messageInfo_ResponseMessageSearchResponse.Size(m)
}
func (m *ResponseMessageSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessageSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessageSearchResponse proto.InternalMessageInfo

func (m *ResponseMessageSearchResponse) GetSearchResults() []*MessageSearchItem {
	if m != nil {
		return m.SearchResults
	}
	return nil
}

func (m *ResponseMessageSearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ResponseMessageSearchResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ResponseMessageSearchResponse) GetLoadMoreState() *wrappers.BytesValue {
	if m != nil {
		return m.LoadMoreState
	}
	return nil
}

func (m *ResponseMessageSearchResponse) GetUserOutPeers() []*UserOutPeer {
	if m != nil {
		return m.UserOutPeers
	}
	return nil
}

func (m *ResponseMessageSearchResponse) GetGroupOutPeers() []*GroupOutPeer {
	if m != nil {
		return m.GroupOutPeers
	}
	return nil
}

// Performing message search
type RequestMessageSearch struct {
	Query                *SearchCondition     `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Optimizations        []UpdateOptimization `protobuf:"varint,2,rep,packed,name=optimizations,enum=dialog.UpdateOptimization" json:"optimizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestMessageSearch) Reset()         { *m = RequestMessageSearch{} }
func (m *RequestMessageSearch) String() string { return proto.CompactTextString(m) }
func (*RequestMessageSearch) ProtoMessage()    {}
func (*RequestMessageSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{22}
}
func (m *RequestMessageSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMessageSearch.Unmarshal(m, b)
}
func (m *RequestMessageSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMessageSearch.Marshal(b, m, deterministic)
}
func (dst *RequestMessageSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMessageSearch.Merge(dst, src)
}
func (m *RequestMessageSearch) XXX_Size() int {
	return xxx_messageInfo_RequestMessageSearch.Size(m)
}
func (m *RequestMessageSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMessageSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMessageSearch proto.InternalMessageInfo

func (m *RequestMessageSearch) GetQuery() *SearchCondition {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *RequestMessageSearch) GetOptimizations() []UpdateOptimization {
	if m != nil {
		return m.Optimizations
	}
	return nil
}

// Performing message search paging
type RequestMessageSearchMore struct {
	LoadMoreState        []byte               `protobuf:"bytes,1,opt,name=load_more_state,json=loadMoreState,proto3" json:"load_more_state,omitempty"`
	Optimizations        []UpdateOptimization `protobuf:"varint,2,rep,packed,name=optimizations,enum=dialog.UpdateOptimization" json:"optimizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestMessageSearchMore) Reset()         { *m = RequestMessageSearchMore{} }
func (m *RequestMessageSearchMore) String() string { return proto.CompactTextString(m) }
func (*RequestMessageSearchMore) ProtoMessage()    {}
func (*RequestMessageSearchMore) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{23}
}
func (m *RequestMessageSearchMore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMessageSearchMore.Unmarshal(m, b)
}
func (m *RequestMessageSearchMore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMessageSearchMore.Marshal(b, m, deterministic)
}
func (dst *RequestMessageSearchMore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMessageSearchMore.Merge(dst, src)
}
func (m *RequestMessageSearchMore) XXX_Size() int {
	return xxx_messageInfo_RequestMessageSearchMore.Size(m)
}
func (m *RequestMessageSearchMore) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMessageSearchMore.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMessageSearchMore proto.InternalMessageInfo

func (m *RequestMessageSearchMore) GetLoadMoreState() []byte {
	if m != nil {
		return m.LoadMoreState
	}
	return nil
}

func (m *RequestMessageSearchMore) GetOptimizations() []UpdateOptimization {
	if m != nil {
		return m.Optimizations
	}
	return nil
}

type RequestSimpleSearch struct {
	Criteria             []*SimpleSearchCondition `protobuf:"bytes,1,rep,name=criteria" json:"criteria,omitempty"`
	Optimizations        []UpdateOptimization     `protobuf:"varint,2,rep,packed,name=optimizations,enum=dialog.UpdateOptimization" json:"optimizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RequestSimpleSearch) Reset()         { *m = RequestSimpleSearch{} }
func (m *RequestSimpleSearch) String() string { return proto.CompactTextString(m) }
func (*RequestSimpleSearch) ProtoMessage()    {}
func (*RequestSimpleSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{24}
}
func (m *RequestSimpleSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSimpleSearch.Unmarshal(m, b)
}
func (m *RequestSimpleSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSimpleSearch.Marshal(b, m, deterministic)
}
func (dst *RequestSimpleSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSimpleSearch.Merge(dst, src)
}
func (m *RequestSimpleSearch) XXX_Size() int {
	return xxx_messageInfo_RequestSimpleSearch.Size(m)
}
func (m *RequestSimpleSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSimpleSearch.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSimpleSearch proto.InternalMessageInfo

func (m *RequestSimpleSearch) GetCriteria() []*SimpleSearchCondition {
	if m != nil {
		return m.Criteria
	}
	return nil
}

func (m *RequestSimpleSearch) GetOptimizations() []UpdateOptimization {
	if m != nil {
		return m.Optimizations
	}
	return nil
}

type RequestSimpleSearchMore struct {
	LoadMoreState        []byte               `protobuf:"bytes,1,opt,name=load_more_state,json=loadMoreState,proto3" json:"load_more_state,omitempty"`
	Optimizations        []UpdateOptimization `protobuf:"varint,2,rep,packed,name=optimizations,enum=dialog.UpdateOptimization" json:"optimizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestSimpleSearchMore) Reset()         { *m = RequestSimpleSearchMore{} }
func (m *RequestSimpleSearchMore) String() string { return proto.CompactTextString(m) }
func (*RequestSimpleSearchMore) ProtoMessage()    {}
func (*RequestSimpleSearchMore) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_f95f3a19a18fc042, []int{25}
}
func (m *RequestSimpleSearchMore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSimpleSearchMore.Unmarshal(m, b)
}
func (m *RequestSimpleSearchMore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSimpleSearchMore.Marshal(b, m, deterministic)
}
func (dst *RequestSimpleSearchMore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSimpleSearchMore.Merge(dst, src)
}
func (m *RequestSimpleSearchMore) XXX_Size() int {
	return xxx_messageInfo_RequestSimpleSearchMore.Size(m)
}
func (m *RequestSimpleSearchMore) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSimpleSearchMore.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSimpleSearchMore proto.InternalMessageInfo

func (m *RequestSimpleSearchMore) GetLoadMoreState() []byte {
	if m != nil {
		return m.LoadMoreState
	}
	return nil
}

func (m *RequestSimpleSearchMore) GetOptimizations() []UpdateOptimization {
	if m != nil {
		return m.Optimizations
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleContactSearchCondition)(nil), "dialog.SimpleContactSearchCondition")
	proto.RegisterType((*SimpleMessageSearchCondition)(nil), "dialog.SimpleMessageSearchCondition")
	proto.RegisterType((*SimplePeerSearchCondition)(nil), "dialog.SimplePeerSearchCondition")
	proto.RegisterType((*SimpleUserProfileSearchCondition)(nil), "dialog.SimpleUserProfileSearchCondition")
	proto.RegisterType((*Criterion)(nil), "dialog.criterion")
	proto.RegisterType((*SimpleSearchCondition)(nil), "dialog.SimpleSearchCondition")
	proto.RegisterType((*SearchCondition)(nil), "dialog.SearchCondition")
	proto.RegisterType((*SearchPeerTypeCondition)(nil), "dialog.SearchPeerTypeCondition")
	proto.RegisterType((*SearchPieceText)(nil), "dialog.SearchPieceText")
	proto.RegisterType((*SearchAndCondition)(nil), "dialog.SearchAndCondition")
	proto.RegisterType((*SearchOrCondition)(nil), "dialog.SearchOrCondition")
	proto.RegisterType((*SearchPeerCondition)(nil), "dialog.SearchPeerCondition")
	proto.RegisterType((*SearchPeerContentType)(nil), "dialog.SearchPeerContentType")
	proto.RegisterType((*SearchSenderIdConfition)(nil), "dialog.SearchSenderIdConfition")
	proto.RegisterType((*PeerSearchResult)(nil), "dialog.PeerSearchResult")
	proto.RegisterType((*RequestPeerSearch)(nil), "dialog.RequestPeerSearch")
	proto.RegisterType((*ResponsePeerSearch)(nil), "dialog.ResponsePeerSearch")
	proto.RegisterType((*RequestResolvePeer)(nil), "dialog.RequestResolvePeer")
	proto.RegisterType((*ResponseResolvePeer)(nil), "dialog.ResponseResolvePeer")
	proto.RegisterType((*MessageSearchResult)(nil), "dialog.MessageSearchResult")
	proto.RegisterType((*MessageSearchItem)(nil), "dialog.MessageSearchItem")
	proto.RegisterType((*ResponseMessageSearchResponse)(nil), "dialog.ResponseMessageSearchResponse")
	proto.RegisterType((*RequestMessageSearch)(nil), "dialog.RequestMessageSearch")
	proto.RegisterType((*RequestMessageSearchMore)(nil), "dialog.RequestMessageSearchMore")
	proto.RegisterType((*RequestSimpleSearch)(nil), "dialog.RequestSimpleSearch")
	proto.RegisterType((*RequestSimpleSearchMore)(nil), "dialog.RequestSimpleSearchMore")
	proto.RegisterEnum("dialog.SearchPeerType", SearchPeerType_name, SearchPeerType_value)
	proto.RegisterEnum("dialog.SearchContentType", SearchContentType_name, SearchContentType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	PeerSearch(ctx context.Context, in *RequestPeerSearch, opts ...grpc.CallOption) (*ResponsePeerSearch, error)
	ResolvePeer(ctx context.Context, in *RequestResolvePeer, opts ...grpc.CallOption) (*ResponseResolvePeer, error)
	MessageSearch(ctx context.Context, in *RequestMessageSearch, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error)
	MessageSearchMore(ctx context.Context, in *RequestMessageSearchMore, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error)
	SimpleSearch(ctx context.Context, in *RequestSimpleSearch, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error)
	SimpleSearchMore(ctx context.Context, in *RequestSimpleSearchMore, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) PeerSearch(ctx context.Context, in *RequestPeerSearch, opts ...grpc.CallOption) (*ResponsePeerSearch, error) {
	out := new(ResponsePeerSearch)
	err := c.cc.Invoke(ctx, "/dialog.Search/PeerSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) ResolvePeer(ctx context.Context, in *RequestResolvePeer, opts ...grpc.CallOption) (*ResponseResolvePeer, error) {
	out := new(ResponseResolvePeer)
	err := c.cc.Invoke(ctx, "/dialog.Search/ResolvePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) MessageSearch(ctx context.Context, in *RequestMessageSearch, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error) {
	out := new(ResponseMessageSearchResponse)
	err := c.cc.Invoke(ctx, "/dialog.Search/MessageSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) MessageSearchMore(ctx context.Context, in *RequestMessageSearchMore, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error) {
	out := new(ResponseMessageSearchResponse)
	err := c.cc.Invoke(ctx, "/dialog.Search/MessageSearchMore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SimpleSearch(ctx context.Context, in *RequestSimpleSearch, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error) {
	out := new(ResponseMessageSearchResponse)
	err := c.cc.Invoke(ctx, "/dialog.Search/SimpleSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) SimpleSearchMore(ctx context.Context, in *RequestSimpleSearchMore, opts ...grpc.CallOption) (*ResponseMessageSearchResponse, error) {
	out := new(ResponseMessageSearchResponse)
	err := c.cc.Invoke(ctx, "/dialog.Search/SimpleSearchMore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	PeerSearch(context.Context, *RequestPeerSearch) (*ResponsePeerSearch, error)
	ResolvePeer(context.Context, *RequestResolvePeer) (*ResponseResolvePeer, error)
	MessageSearch(context.Context, *RequestMessageSearch) (*ResponseMessageSearchResponse, error)
	MessageSearchMore(context.Context, *RequestMessageSearchMore) (*ResponseMessageSearchResponse, error)
	SimpleSearch(context.Context, *RequestSimpleSearch) (*ResponseMessageSearchResponse, error)
	SimpleSearchMore(context.Context, *RequestSimpleSearchMore) (*ResponseMessageSearchResponse, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_PeerSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPeerSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).PeerSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/PeerSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).PeerSearch(ctx, req.(*RequestPeerSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_ResolvePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestResolvePeer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).ResolvePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/ResolvePeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).ResolvePeer(ctx, req.(*RequestResolvePeer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_MessageSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessageSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).MessageSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/MessageSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).MessageSearch(ctx, req.(*RequestMessageSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_MessageSearchMore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessageSearchMore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).MessageSearchMore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/MessageSearchMore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).MessageSearchMore(ctx, req.(*RequestMessageSearchMore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SimpleSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSimpleSearch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SimpleSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/SimpleSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SimpleSearch(ctx, req.(*RequestSimpleSearch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Search_SimpleSearchMore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSimpleSearchMore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).SimpleSearchMore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dialog.Search/SimpleSearchMore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).SimpleSearchMore(ctx, req.(*RequestSimpleSearchMore))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dialog.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeerSearch",
			Handler:    _Search_PeerSearch_Handler,
		},
		{
			MethodName: "ResolvePeer",
			Handler:    _Search_ResolvePeer_Handler,
		},
		{
			MethodName: "MessageSearch",
			Handler:    _Search_MessageSearch_Handler,
		},
		{
			MethodName: "MessageSearchMore",
			Handler:    _Search_MessageSearchMore_Handler,
		},
		{
			MethodName: "SimpleSearch",
			Handler:    _Search_SimpleSearch_Handler,
		},
		{
			MethodName: "SimpleSearchMore",
			Handler:    _Search_SimpleSearchMore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_search_f95f3a19a18fc042) }

var fileDescriptor_search_f95f3a19a18fc042 = []byte{
	// 1809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5f, 0x6f, 0xe3, 0x58,
	0x15, 0xaf, 0x9b, 0x34, 0x6d, 0x4e, 0xd3, 0x36, 0xbd, 0x9d, 0x4e, 0xd3, 0xb4, 0xa5, 0xad, 0x61,
	0x86, 0xd1, 0x2c, 0x4a, 0x66, 0x3b, 0xbb, 0x5a, 0x31, 0x20, 0x75, 0x9b, 0x6c, 0x98, 0x94, 0x99,
	0x49, 0xb2, 0x4e, 0xba, 0x30, 0x02, 0x29, 0x72, 0xed, 0x3b, 0x19, 0xaf, 0x1c, 0xdb, 0x6b, 0x3b,
	0x03, 0x05, 0x09, 0xa4, 0x7d, 0x41, 0x9a, 0x47, 0xf8, 0x04, 0xbc, 0xf2, 0x02, 0xef, 0x3c, 0xac,
	0x84, 0xc4, 0x27, 0xe0, 0x89, 0xd7, 0x11, 0x4f, 0xfb, 0x05, 0xe0, 0x11, 0xdd, 0x3f, 0x8e, 0xaf,
	0xaf, 0x9d, 0xb4, 0x45, 0x02, 0xf1, 0xd4, 0xe6, 0x9e, 0xf3, 0xfb, 0x9d, 0x73, 0xcf, 0xbf, 0x7b,
	0x0c, 0xa5, 0x00, 0xeb, 0xbe, 0xf1, 0xba, 0xe6, 0xf9, 0x6e, 0xe8, 0xa2, 0x82, 0x69, 0xe9, 0xb6,
	0x3b, 0xaa, 0x7e, 0x63, 0xe4, 0xba, 0x23, 0x1b, 0xd7, 0xe9, 0xe9, 0xe5, 0xe4, 0x55, 0xfd, 0x67,
	0xbe, 0xee, 0x79, 0xd8, 0x0f, 0x98, 0x5e, 0x75, 0x9f, 0xcb, 0x75, 0xcf, 0xaa, 0xeb, 0x8e, 0xe3,
	0x86, 0x7a, 0x68, 0xb9, 0x4e, 0x24, 0xdd, 0x34, 0xf1, 0x2b, 0xcb, 0xb1, 0xc4, 0xa3, 0xd2, 0xc8,
	0x77, 0x27, 0x5e, 0xf4, 0x6b, 0xd5, 0xc3, 0x31, 0xd7, 0xc6, 0x18, 0x07, 0x81, 0x3e, 0xb2, 0x9c,
	0x51, 0x24, 0x9d, 0x04, 0xb1, 0x74, 0x6b, 0x6c, 0x05, 0x06, 0xb6, 0x6d, 0xdd, 0xc1, 0xee, 0x24,
	0x3a, 0xdc, 0x0e, 0x0c, 0xdd, 0xd6, 0xbd, 0xcb, 0x3a, 0xff, 0xcb, 0x8e, 0xd5, 0x13, 0xd8, 0xef,
	0x5b, 0x63, 0xcf, 0xc6, 0x4d, 0xd7, 0x09, 0x75, 0x23, 0xec, 0xd3, 0xab, 0x35, 0x5d, 0xc7, 0xa4,
	0xbe, 0x20, 0x04, 0xf9, 0x10, 0xff, 0x3c, 0xac, 0x28, 0x47, 0xca, 0x83, 0xa2, 0x46, 0xff, 0x57,
	0x7f, 0xab, 0x44, 0xa0, 0x17, 0xd4, 0x0d, 0x2c, 0x83, 0x8e, 0x20, 0x4f, 0xbc, 0xa5, 0xa0, 0xd5,
	0x93, 0x52, 0x8d, 0x45, 0xa8, 0xd6, 0xc3, 0xd8, 0xd7, 0xa8, 0x64, 0x4a, 0xbb, 0x18, 0xd3, 0xa2,
	0xef, 0x43, 0xc9, 0x70, 0x9d, 0x10, 0x3b, 0xe1, 0x30, 0xbc, 0xf2, 0x70, 0x25, 0x77, 0xa4, 0x3c,
	0x58, 0x3f, 0xd9, 0x8d, 0xd0, 0x53, 0x23, 0x44, 0x63, 0x70, 0xe5, 0x61, 0x6d, 0xd5, 0x88, 0x7f,
	0xa8, 0x5f, 0x2a, 0xb0, 0xcb, 0x9c, 0x22, 0x66, 0x64, 0x8f, 0x1e, 0x43, 0x91, 0xd8, 0x65, 0xc4,
	0x0a, 0x25, 0xbe, 0x9b, 0x24, 0x26, 0x28, 0xca, 0xba, 0xe2, 0xf1, 0xff, 0xd0, 0x23, 0xc1, 0xc9,
	0xd5, 0x93, 0xfd, 0x1a, 0x4b, 0x60, 0x2d, 0x4a, 0x70, 0xad, 0x1f, 0xfa, 0x96, 0x33, 0xfa, 0x4c,
	0xb7, 0x27, 0x98, 0x47, 0xa6, 0x05, 0x47, 0xcc, 0x87, 0x8b, 0x00, 0xfb, 0x3d, 0xdf, 0x7d, 0x65,
	0xd9, 0xa9, 0xe0, 0x1c, 0x43, 0xe9, 0x8b, 0x09, 0xf6, 0xaf, 0x86, 0x01, 0x85, 0xf3, 0xc8, 0xae,
	0xd2, 0x33, 0xc6, 0xa8, 0xae, 0x42, 0xd1, 0xf0, 0xad, 0x10, 0xfb, 0x96, 0xeb, 0xa8, 0x7f, 0x5c,
	0x84, 0x6d, 0x46, 0x2a, 0x33, 0x7d, 0x0c, 0xcb, 0x06, 0xcb, 0x1a, 0x8f, 0xf4, 0xb7, 0xa6, 0x57,
	0x9a, 0x93, 0xd2, 0xf6, 0x82, 0x16, 0xc1, 0x08, 0x03, 0xab, 0x24, 0xcc, 0x2f, 0x29, 0x31, 0x64,
	0xe7, 0x97, 0x30, 0x70, 0x18, 0xfa, 0x88, 0xa7, 0x3a, 0x47, 0xe1, 0xc7, 0x49, 0x78, 0x46, 0x26,
	0xda, 0x0b, 0xbc, 0x02, 0x9e, 0x03, 0xad, 0x59, 0x1e, 0xa4, 0x4a, 0x9e, 0xe2, 0x1f, 0x24, 0xf1,
	0xb3, 0xa3, 0xd8, 0x5e, 0xd0, 0x44, 0x78, 0x23, 0x11, 0xb1, 0xbf, 0xe7, 0x61, 0x43, 0x8e, 0xd5,
	0x4f, 0x60, 0x27, 0x48, 0xe4, 0x79, 0x2a, 0xe2, 0xb1, 0x3b, 0xcc, 0x2e, 0x07, 0xd1, 0xe2, 0x2c,
	0x06, 0xd4, 0x84, 0x0d, 0x2e, 0xb2, 0xb0, 0x81, 0x07, 0x71, 0xcd, 0xec, 0x48, 0xa4, 0x91, 0xb8,
	0xbd, 0xa0, 0xc9, 0x08, 0xf4, 0x1c, 0x10, 0x3b, 0x3a, 0x73, 0xcc, 0xd8, 0x39, 0x16, 0xd7, 0x6a,
	0x92, 0x47, 0xd4, 0x68, 0x2f, 0x68, 0x19, 0x38, 0x74, 0x0e, 0x9b, 0xec, 0xb4, 0xeb, 0xc7, 0x64,
	0x2c, 0xc8, 0x52, 0x47, 0x09, 0x0a, 0xed, 0x05, 0x2d, 0x8d, 0x42, 0x5d, 0xd8, 0x8a, 0x2f, 0x1e,
	0x93, 0x2d, 0x51, 0xb2, 0xbd, 0x74, 0xd8, 0x44, 0xba, 0x2c, 0x24, 0xba, 0x80, 0xed, 0xc4, 0x71,
	0xd4, 0xc3, 0x95, 0x02, 0xa5, 0x3c, 0xc8, 0xa4, 0x8c, 0x94, 0xda, 0x0b, 0x5a, 0x36, 0x3a, 0x4e,
	0x71, 0x1f, 0x3b, 0x26, 0xf6, 0xcf, 0x49, 0x34, 0x5e, 0x31, 0x5f, 0x97, 0xb3, 0x52, 0x9c, 0x52,
	0x8b, 0x53, 0x9c, 0x12, 0x35, 0x0a, 0x90, 0xbf, 0x74, 0xcd, 0x2b, 0xf5, 0xa7, 0xb0, 0x33, 0xa3,
	0x40, 0xd0, 0xd9, 0x8d, 0x67, 0x4c, 0xa3, 0xf4, 0xf6, 0xeb, 0x47, 0x2b, 0x50, 0x78, 0x6d, 0x99,
	0x26, 0x76, 0xe2, 0x89, 0xa3, 0x7e, 0x18, 0x15, 0x6e, 0x5c, 0x16, 0x2a, 0x2c, 0xd1, 0xd1, 0xc0,
	0xe6, 0x84, 0x84, 0x64, 0x22, 0xf5, 0x25, 0xa0, 0x74, 0x61, 0xa0, 0x26, 0x14, 0x75, 0xc7, 0x1c,
	0x46, 0xe8, 0x5c, 0xba, 0x1e, 0xa7, 0xba, 0x8d, 0xb5, 0xb7, 0x5f, 0x3f, 0x2a, 0xc2, 0xf2, 0x1b,
	0x2b, 0xb0, 0x2e, 0x6d, 0xac, 0xad, 0xe8, 0x8e, 0xf9, 0x29, 0xa5, 0xfe, 0x0c, 0x36, 0x53, 0x65,
	0x82, 0xce, 0x60, 0xc5, 0xf5, 0x39, 0xf1, 0xe2, 0xad, 0x88, 0x97, 0x5d, 0x9f, 0xf1, 0x9e, 0xc3,
	0x56, 0x46, 0xc5, 0xa0, 0x93, 0xc4, 0xcb, 0xb1, 0x11, 0xb1, 0x76, 0x27, 0x21, 0xd1, 0x93, 0xd9,
	0xa8, 0xae, 0x6a, 0xc2, 0x76, 0x66, 0xa5, 0xa0, 0x67, 0xd2, 0x83, 0xa2, 0x5c, 0xf3, 0xa0, 0xc8,
	0xf4, 0x89, 0xf7, 0xa5, 0x15, 0x25, 0x3e, 0x55, 0x1b, 0xe8, 0x21, 0x14, 0x03, 0x7a, 0x38, 0xb4,
	0x4c, 0x6a, 0x64, 0x29, 0x15, 0xcf, 0x80, 0x83, 0xd4, 0x3f, 0xe7, 0xa1, 0x1c, 0x8f, 0x45, 0x0d,
	0x07, 0x13, 0x3b, 0x44, 0xf5, 0xd9, 0xef, 0x65, 0xe6, 0x95, 0x49, 0x51, 0x84, 0x56, 0x68, 0xb3,
	0xa9, 0x9d, 0x2a, 0x0a, 0x2a, 0x42, 0x4f, 0xa0, 0x18, 0xbc, 0x76, 0xfd, 0xd0, 0xd1, 0xc7, 0xb8,
	0x52, 0xbc, 0xc1, 0x13, 0x16, 0xab, 0x93, 0xe1, 0x6c, 0xe2, 0xc0, 0xf0, 0x2d, 0x4f, 0x18, 0x42,
	0x73, 0xd1, 0x92, 0x0f, 0x22, 0x1c, 0x75, 0x61, 0x6d, 0x8c, 0xc7, 0x97, 0xd8, 0x0f, 0x86, 0x86,
	0x3b, 0x71, 0x42, 0x3e, 0x87, 0xf6, 0x52, 0x7c, 0xe7, 0x4e, 0xf8, 0xf8, 0x84, 0xd1, 0x49, 0xd7,
	0x2e, 0x71, 0x82, 0x26, 0xc1, 0xa3, 0x47, 0x50, 0x32, 0xf5, 0x10, 0x0f, 0x0d, 0x1f, 0xeb, 0x21,
	0x36, 0xe9, 0x28, 0xca, 0xa5, 0xb2, 0x47, 0x54, 0x9a, 0x4c, 0x03, 0x7d, 0x02, 0xcb, 0x54, 0xd9,
	0xf5, 0xf9, 0x90, 0xb9, 0x8d, 0xf1, 0x08, 0x8a, 0x7e, 0x00, 0x45, 0x2b, 0x18, 0x7a, 0x93, 0x4b,
	0xdb, 0x32, 0xf8, 0x4c, 0xa9, 0xa6, 0x78, 0x1a, 0xae, 0x6b, 0x67, 0xd2, 0xac, 0x58, 0x41, 0x8f,
	0x42, 0xd1, 0x47, 0x94, 0xe7, 0x73, 0xd7, 0x72, 0xb0, 0x59, 0x59, 0xb9, 0x8e, 0x87, 0x00, 0x7f,
	0x48, 0x75, 0xd5, 0xaf, 0x14, 0xd8, 0xd4, 0xf0, 0x17, 0x13, 0x1c, 0x84, 0x71, 0x11, 0xa1, 0xef,
	0xc5, 0x23, 0x62, 0x6e, 0x2f, 0x66, 0xcd, 0x0e, 0x92, 0x1c, 0xd7, 0x0b, 0xad, 0xb1, 0xf5, 0x0b,
	0xb6, 0x8f, 0xd2, 0x86, 0x5e, 0x8f, 0x5f, 0x9c, 0x0b, 0x8f, 0xc4, 0xb1, 0x2b, 0xa8, 0xc8, 0xf7,
	0x4a, 0xe2, 0x9f, 0xec, 0xbf, 0x3b, 0xdd, 0x85, 0x1d, 0x6b, 0x5c, 0x33, 0xed, 0x51, 0x6d, 0xe4,
	0x7b, 0x46, 0xed, 0xa9, 0xef, 0x19, 0xdc, 0x6b, 0xf5, 0x0f, 0x8b, 0x80, 0x34, 0x1c, 0x78, 0xae,
	0x13, 0x08, 0xeb, 0x01, 0x3a, 0x85, 0x75, 0x36, 0x79, 0x87, 0x3e, 0x6d, 0x89, 0x80, 0xdf, 0xa5,
	0x22, 0xf6, 0x82, 0xd8, 0x33, 0xda, 0x5a, 0x20, 0xfc, 0x0a, 0x48, 0x47, 0xd0, 0x15, 0x98, 0xcf,
	0xa3, 0x69, 0x0f, 0x91, 0x15, 0x42, 0x63, 0x22, 0x74, 0x0f, 0x0a, 0x6c, 0xa5, 0xae, 0xe4, 0xa8,
	0xd2, 0x5a, 0xa4, 0xf4, 0x94, 0x9c, 0x6a, 0x5c, 0x88, 0x4e, 0x00, 0x88, 0xfe, 0x90, 0x2e, 0xdc,
	0x95, 0x3c, 0x55, 0xdd, 0x12, 0xf9, 0xf8, 0x34, 0xd2, 0x8a, 0x74, 0x03, 0x21, 0x5a, 0xe8, 0x43,
	0x58, 0xa5, 0x68, 0x0e, 0x5a, 0xa2, 0xa0, 0x3b, 0x09, 0xfe, 0x08, 0x05, 0x54, 0x91, 0xc2, 0x9e,
	0x1c, 0xbc, 0x3b, 0xad, 0x42, 0x25, 0x1d, 0x2b, 0x16, 0x1f, 0x75, 0x48, 0x62, 0x45, 0xe3, 0xa6,
	0xe1, 0xc0, 0xb5, 0xdf, 0xd0, 0x88, 0xa1, 0xf7, 0xc4, 0xc6, 0x66, 0xaf, 0x82, 0x94, 0x91, 0x58,
	0x7e, 0x4d, 0x36, 0x5e, 0xc2, 0x56, 0x64, 0x4c, 0xb4, 0xf0, 0xcd, 0xb9, 0x53, 0x98, 0xcd, 0xa0,
	0xeb, 0x7c, 0xff, 0xa7, 0x02, 0x5b, 0x89, 0xf5, 0xf1, 0x3f, 0x9d, 0x75, 0x87, 0x90, 0xf3, 0x2d,
	0x93, 0x4e, 0xba, 0x54, 0x8f, 0x13, 0x09, 0x3a, 0x86, 0x3c, 0x29, 0x51, 0x3a, 0xa5, 0x52, 0x1a,
	0x54, 0x94, 0x9c, 0xd0, 0xf9, 0xb9, 0x13, 0x1a, 0x9d, 0xb2, 0xad, 0x1a, 0x3b, 0x21, 0x5f, 0x71,
	0xa6, 0x8f, 0x38, 0xbf, 0x0e, 0x7f, 0x31, 0xd2, 0x53, 0x82, 0x9d, 0xab, 0x6d, 0xd8, 0x4c, 0x5c,
	0xfc, 0x3c, 0xc4, 0x63, 0xf4, 0x18, 0x0a, 0xac, 0xb2, 0xf9, 0xc5, 0xf7, 0x24, 0xd2, 0x44, 0x6d,
	0x73, 0x55, 0xf5, 0x5d, 0x0e, 0x0e, 0xa2, 0x80, 0xca, 0x7a, 0xf4, 0x10, 0x75, 0x67, 0xf4, 0xcd,
	0x6e, 0x26, 0x3d, 0xf1, 0x24, 0xd5, 0xbd, 0xc9, 0x3e, 0x7a, 0x7f, 0x4e, 0x1f, 0xc9, 0x50, 0xde,
	0x56, 0x1f, 0xcc, 0x6d, 0x2b, 0x19, 0x14, 0x75, 0xd9, 0xa7, 0xb0, 0x61, 0xbb, 0xba, 0x39, 0x1c,
	0xbb, 0x3e, 0x1e, 0x06, 0x21, 0x49, 0xe0, 0xac, 0x67, 0xa1, 0x71, 0x15, 0xe2, 0x20, 0xeb, 0x95,
	0x59, 0x23, 0x0c, 0x2f, 0x5c, 0x1f, 0xf7, 0x09, 0x1e, 0xb5, 0x61, 0x9d, 0x36, 0xae, 0x3b, 0x09,
	0x13, 0x7d, 0x98, 0xd5, 0xbc, 0xa9, 0x07, 0x66, 0x12, 0xcb, 0x02, 0xf4, 0x0c, 0x36, 0x58, 0x3b,
	0xc7, 0x54, 0x85, 0xd9, 0x2d, 0x9d, 0x0a, 0xe9, 0x48, 0x10, 0x5e, 0xdb, 0xe4, 0x7f, 0x51, 0xe0,
	0x0e, 0xef, 0xc7, 0x44, 0xb2, 0xc4, 0xb1, 0xae, 0xfc, 0xbf, 0x8f, 0xf5, 0xaf, 0x14, 0xa8, 0x64,
	0x5d, 0x82, 0x24, 0x07, 0x7d, 0x90, 0x4e, 0x35, 0xb9, 0x52, 0x69, 0x7e, 0x36, 0xff, 0xc7, 0x37,
	0xf8, 0x93, 0x42, 0x66, 0x21, 0xfd, 0x5f, 0xfc, 0xda, 0x46, 0xdf, 0x85, 0x15, 0xfe, 0x65, 0xa9,
	0xf3, 0xde, 0x3a, 0x48, 0x7e, 0xa4, 0x4a, 0xe9, 0xd0, 0xa6, 0xea, 0xe8, 0xe3, 0x5b, 0xdf, 0xe0,
	0x76, 0x2e, 0xff, 0x5e, 0x81, 0x9d, 0x0c, 0x97, 0x69, 0xcc, 0xef, 0xcf, 0x88, 0xb9, 0x1c, 0xe5,
	0xff, 0xb2, 0x8f, 0x0f, 0x7f, 0x0d, 0xeb, 0xc9, 0x6f, 0x1f, 0x54, 0x85, 0xbb, 0xfd, 0xd6, 0x99,
	0xd6, 0x6c, 0xf7, 0x5a, 0x2d, 0x6d, 0xf0, 0xb2, 0xd7, 0x1a, 0x5e, 0x74, 0x9e, 0x75, 0xba, 0x3f,
	0xea, 0x94, 0x17, 0xd0, 0x2e, 0x6c, 0x4b, 0xb2, 0xa7, 0x5a, 0xf7, 0xa2, 0xd7, 0x2f, 0x2b, 0x68,
	0x0f, 0x76, 0x24, 0x51, 0xb3, 0xdb, 0x19, 0x9c, 0x35, 0x07, 0xfd, 0xf2, 0x62, 0x06, 0xae, 0x77,
	0xd1, 0x78, 0x7e, 0xde, 0x2c, 0xe7, 0x1e, 0xfe, 0x55, 0x89, 0xbe, 0x60, 0xc4, 0x4f, 0x83, 0x03,
	0xd8, 0x65, 0x00, 0x42, 0xd2, 0xea, 0x0c, 0x66, 0xf9, 0x21, 0x8a, 0xcf, 0x3a, 0x2f, 0xcb, 0x4a,
	0xec, 0xbe, 0x28, 0x1a, 0xb4, 0x7e, 0x3c, 0x28, 0x2f, 0xc6, 0x3e, 0x8a, 0xb2, 0xe7, 0xe7, 0x9d,
	0x67, 0xfd, 0x72, 0x0e, 0x1d, 0xc2, 0x5e, 0x5a, 0xf8, 0x49, 0xb7, 0x79, 0xf1, 0xa2, 0xd5, 0x19,
	0xf4, 0xcb, 0x79, 0xb4, 0x0f, 0x95, 0xb4, 0x42, 0xaf, 0xdd, 0x1d, 0x74, 0xfb, 0xe5, 0xa5, 0x93,
	0x7f, 0x2d, 0x41, 0x81, 0x97, 0xe4, 0xe7, 0x00, 0xc2, 0xea, 0x34, 0x1d, 0xf5, 0xa9, 0xc5, 0xb0,
	0x5a, 0x8d, 0x45, 0xf2, 0xc6, 0xa5, 0xde, 0xfb, 0xf2, 0x6f, 0xff, 0xf8, 0xdd, 0xe2, 0xa1, 0x5a,
	0xad, 0xbf, 0x79, 0xbf, 0x4e, 0xd2, 0x56, 0x67, 0x82, 0x7a, 0xac, 0xf3, 0x44, 0x79, 0x88, 0x1c,
	0x58, 0x15, 0x37, 0x83, 0xaa, 0x64, 0x4c, 0x90, 0x55, 0xf7, 0x64, 0x6b, 0x82, 0x50, 0xbd, 0x4f,
	0xcd, 0x1d, 0xa9, 0x7b, 0xb2, 0x39, 0x41, 0x89, 0xd8, 0xfb, 0x15, 0xac, 0x25, 0xa7, 0xe0, 0xbe,
	0x64, 0x31, 0x21, 0xad, 0xde, 0x93, 0x6d, 0x66, 0x3e, 0x93, 0xea, 0x03, 0x6a, 0x5d, 0x55, 0x0f,
	0x64, 0xeb, 0x09, 0x75, 0x62, 0xff, 0xad, 0x22, 0xbd, 0xde, 0xb4, 0x9b, 0x8e, 0xe6, 0x39, 0x41,
	0x34, 0x6e, 0xea, 0xc8, 0x77, 0xa8, 0x23, 0xf7, 0xd5, 0xe3, 0xb9, 0x8e, 0x10, 0x46, 0xe2, 0xcc,
	0x2f, 0xa1, 0x94, 0x98, 0x45, 0x7b, 0x92, 0x1b, 0xa2, 0xf0, 0xa6, 0x1e, 0x7c, 0x9b, 0x7a, 0x70,
	0xac, 0xee, 0xcb, 0x1e, 0x88, 0x64, 0xc4, 0xf8, 0x6f, 0x14, 0x28, 0xa7, 0xc6, 0xca, 0xe1, 0x1c,
	0x0f, 0x6e, 0x13, 0x87, 0xf7, 0xa8, 0x17, 0xf7, 0xd4, 0xa3, 0x79, 0x5e, 0xf0, 0x30, 0x34, 0x76,
	0xdf, 0x9d, 0xde, 0x85, 0x3b, 0xe2, 0x84, 0x09, 0xb0, 0xff, 0xc6, 0x32, 0x70, 0x70, 0x59, 0xa0,
	0x4b, 0xc2, 0xe3, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xce, 0x99, 0x8d, 0xeb, 0x93, 0x17, 0x00,
	0x00,
}
