{
 "title": "stress-test-bots",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   { "name": "period", "label": "rate period", "query": "15s,30s,1m" }
  ]
 },
 "panels": [
  {
   "title": "Bots Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_client_handled_total{job=\"$job\", grpc_method=\"SignUp\"}"
    }
   ]
  },
  {
   "title": "grpc call rate (rate period=$period)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_client_msg_sent_total{job=\"$job\"}[$period])\n",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "rpc errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_client_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code!=\"OK\"}",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "rpc call duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_client_handling_seconds_sum{job=\"$job\"}[1m]) / rate(grpc_client_handling_seconds_count{job=\"$job\"}[1m]) ",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "grpc failures rate",
   "type": "graph",
   "description": "grpc failures rate, aggregated by 1min",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_method)\n / \nsum(rate(grpc_client_handled_total{job=\"$job\",grpc_type=\"unary\"}[1m])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Bots read/right activity (rate period=$period)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_client_handled_total{job=\"$job\", grpc_service=\"dialog.Messaging\", grpc_code=\"OK\"}[$period])) by(grpc_method)",
     "legendFormat": "{{grpc_method}} avg rps"
    }
   ]
  }
 ]
}